---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-foo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL